Propagate more Device and Entity properties
net-daemon/netdaemon pull request #1114
Opened 2024-06-09 03:05 UTC by zb140

## Proposed change

I mentioned on Discord a few days ago that I have a use case where it would be helpful to be able to get Manufacturer and Model information for some devices, or to check which integration added an entity.  In my case, I have an entity that I looked up by label, and it could have one of a handful of services that could be used to interact with it. I'd like to find a way to decide which service to use based only on the entity itself, which is much easier if I can tell specifically what kind of device it is.

The data I needed is actually already being provided by the Home Assistant API, it just wasn't being propagated up to the registry objects. This change adds the missing fields

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2024-06-13 05:53 UTC, FrankBakkerNl approved these changes

2024-06-14 05:28 UTC, FrankBakkerNl approved these changes

2024-06-19 18:44 UTC, helto4real commented
Looks great, thanks. Just fix the errors so the build works please. @zb140

2024-06-19 18:47 UTC, helto4real requested changes
Looks great, thanks. Just fix the errors so the build works please. @zb140 Looks like the suppressions did not work.

2024-06-20 19:06 UTC, helto4real approved these changes

2024-06-20 19:07 UTC, merged