Make restart logic progressive and other small fixes
net-daemon/netdaemon pull request #1129
Opened 2024-06-30 07:23 UTC by helto4real

## Breaking change

## Proposed change

Fixes in this PR:
### Progressive reconnect timeouts
To avoid too many tries it will increase the timeout per retry by a factor 2 starting with 5 seconds

### The registry updated log will now be a debug log
Recent versions of HA updates the registries more often and possible flooding the outputlog. This log is now made a debug log instead.

### Fix the problem that the correct version does not show on start
The github action that push to Nuget did not successfully updated version information. The default message also changed  to reflect the actual behaviour. The version is not known when using a local built NetDaemon runtime. The version will then be `local build`. Offical built versions will show the correct version.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] The code compiles without warnings (code quality check)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration are added/changed:

- [ ] Documentation added/updated for http://netdaemon.xtz

[Docs repository]: https://github.com/net-daemon/docs
[Developer documentation]: https://netdaemon.xyz/docs/developer/

2024-06-30 08:01 UTC, helto4real commented
The CI is failing due to a deprecated call that been removed in the beta. Another pr fixes this.

2024-06-30 08:37 UTC, FrankBakkerNl commented on src/Client/NetDaemon.HassClient/Internal/HomeAssistantRunner.cs
> +        var progressiveTimeout = new ProgressiveTimeout((int)timeout.TotalSeconds, MaxTimeoutInSeconds, 2.0);
The time span comes in as a parameter, which implies the caller of this method can use any timespan he wants, not just a round number of seconds. Allowing this as a parameter, by then not using that specific value but the progressive Timeout seems like not doing what the caller expects

2024-06-30 09:37 UTC, FrankBakkerNl commented on src/Client/NetDaemon.HassClient/Internal/HomeAssistantRunner.cs
> +        var progressiveTimeout = new ProgressiveTimeout((int)timeout.TotalSeconds, MaxTimeoutInSeconds, 2.0);
ProgressiveTimeout could be passed a Timespan iso an int, or maybe the ticks iso the seconds to avoid unneccary rounding

2024-06-30 15:05 UTC, helto4real commented on src/Client/NetDaemon.HassClient/Internal/HomeAssistantRunner.cs
> +        var progressiveTimeout = new ProgressiveTimeout((int)timeout.TotalSeconds, MaxTimeoutInSeconds, 2.0);
Good suggestions, I fixed that now.

2024-06-30 17:41 UTC, Barsonax requested changes

2024-06-30 17:41 UTC, Barsonax commented on src/Client/NetDaemon.HassClient/Internal/Helpers/ProgressiveTimeout.cs
> +        if (initialTimeout <= TimeSpan.Zero)
I would use ArgumentOutOfRangeException.ThrowIfLessThanOrEqual here for 2 reasons:
- Its simpler
- Leads to faster code due to the method size being smaller (throwing an exception makes the method body bigger)

2024-06-30 17:41 UTC, Barsonax commented on src/Client/NetDaemon.HassClient/Internal/Helpers/ProgressiveTimeout.cs
> +        if (maxTimeout < initialTimeout)
I think the comparison here should be less than or equal so it matches the message

2024-07-01 02:24 UTC, helto4real commented on src/Client/NetDaemon.HassClient/Internal/Helpers/ProgressiveTimeout.cs
> +        if (initialTimeout <= TimeSpan.Zero)
Yea I tend forget these exists... thanks!

2024-07-01 02:24 UTC, helto4real commented on src/Client/NetDaemon.HassClient/Internal/Helpers/ProgressiveTimeout.cs
> +        if (maxTimeout < initialTimeout)
Good find this is  a logic error indeed.

2024-07-01 04:10 UTC, Barsonax approved these changes

2024-07-01 04:10 UTC, merged