Properly deserialize context when deserializing state in the entity state cache
net-daemon/netdaemon pull request #1157
Opened 2024-08-22 17:10 UTC by nuttytree

## Proposed change
Add JsonPropertyName attributes to properties in the Context object so that they properly deserialize when EntityStateCache deserializes the State object.

## Type of change
- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information
- This PR fixes or closes issue: fixes #1156 

## Checklist
- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] The code compiles without warnings (code quality check)
- [x] Tests have been added to verify that the new code works.

2024-08-23 22:09 UTC, FrankBakkerNl requested changes
I think the fix is good, was not aware of this issue. What was the actual behavior you found?

It must have been introduced with the recent lazy deserialisation of state changes.

I think the tests you updated do not really validate this fix. I even expect them to also pass without the fix because they do not depend not depend. A better test would be to deserialize actually JSON data with the names with _ in them.

2024-08-24 18:02 UTC, Barsonax commented
> It must have been introduced with the recent lazy deserialisation of state changes.

If this worked before its probably because JsonSerializerOptions used with with JsonNamingPolicy.CamelCase. If that is the case then the proper fix is to pass in those options again.

2024-08-24 21:47 UTC, helto4real commented on src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityStateCacheTest.cs
> +        cache.GetState(entityId)!.Context!.Id.Should().NotBeNullOrEmpty();
Why not just test the actual value?

2024-08-24 21:50 UTC, helto4real commented
Weird that this have never worked, seeing your fix it is obvious.

2024-08-26 17:10 UTC, nuttytree commented on src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityStateCacheTest.cs
> +        cache.GetState(entityId)!.Context!.Id.Should().NotBeNullOrEmpty();
Updated to test the actual value is the expected value.

2024-08-26 17:13 UTC, nuttytree commented
I have updated the tests with the requested changes.

2024-08-26 18:07 UTC, FrankBakkerNl approved these changes

2024-08-26 18:22 UTC, nuttytree commented on src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityStateCacheTest.cs
> +        cache.GetState(entityId)!.Context!.Id.Should().NotBeNullOrEmpty();
I meant to change all of those but missed that one, I updated that assert also.

2024-09-01 19:23 UTC, helto4real commented
@nuttytree thank you for your contribution. Please make sure you sign the commits in the future. It is for everyones benefit and security.

2024-09-01 19:23 UTC, merged