Part 2 in the move to IOCing the world.
net-daemon/netdaemon pull request #199
Opened 2020-08-27 11:29 UTC by asherw

## Breaking change

Appears to load the 2 hello world apps...

## Proposed change

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Additional information
The goal is to move away from Activator.CreateInstance and to pull these from IOC.

## Checklist

- [X] The code change is tested and works locally.
- [X] Local tests pass. **Your PR cannot be merged unless tests pass**
- [X] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code compiles without warnings (code quality check)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2020-08-27 11:30 UTC, asherw commented on src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs
> +            if (BypassLocalAssemblyLoading())
Do I have this arse about?

2020-08-27 11:36 UTC, asherw commented on src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs
> +                services.AddSingleton<IDaemonAppCompiler, LocalDaemonAppCompiler>();
Split up local app assembly loading vs compiling .cs files from apps folder.

2020-08-27 11:39 UTC, asherw commented on src/DaemonRunner/DaemonRunner/Service/App/DaemonAppCompiler.cs
> +        public IEnumerable<Type> GetApps()
I created this to help with migration.  Allows me to change less code.
I would like to instantiate apps using DI.  

A POC I created worked but I didn't get round to how the apps would react when a re-connection would occur, so see what happens.

2020-08-27 11:46 UTC, asherw commented on src/DaemonRunner/DaemonRunner/Service/App/DaemonCompiler.cs
> +        public static Assembly GetCompiledAppAssembly(out CollectibleAssemblyLoadContext alc, string codeFolder, ILogger logger)
I expect all this to be eventually moved into NetDaemon.Service.App.DaemonAppCompiler.

Future feature, recompile app folder and reload without having to restart docker container?

2020-08-27 11:48 UTC, asherw commented on src/DaemonRunner/DaemonRunner/Service/App/DaemonCompiler.cs
> +                    //embeddedTexts.Add(EmbeddedText.FromSource(csFile, sourceText));
This wasn't being used.  Should this be output somewhere?

2020-08-27 11:50 UTC, asherw commented on src/DaemonRunner/DaemonRunner/Service/RunnerService.cs
> -                    alc.Unload();
alc was already being unloaded right after apps were being loaded in **GetCompiledAppAssembly(out CollectibleAssemblyLoadContext alc, string codeFolder, ILogger logger)**
This caused an exception on app shutdown.

2020-08-27 17:57 UTC, helto4real commented on src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs
> +            if (BypassLocalAssemblyLoading())
Not sure what you asking ?

2020-08-27 18:00 UTC, helto4real commented on src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs
> +            var value = Environment.GetEnvironmentVariable("HASS_DISABLE_LOCAL_ASM");
So this should always be added to the docker file then? When using default container/add-on? Maybe this should be added to normal config?

2020-08-27 18:02 UTC, helto4real commented on src/DaemonRunner/DaemonRunner/Service/App/DaemonAppCompiler.cs
> +        public IEnumerable<Type> GetApps()
I test this manually during development. And yea would be nice to create apps with DI but... still needs to be dynamic. I do not want the user to specify explicit what apps should be compiled.

2020-08-27 18:05 UTC, helto4real commented on src/DaemonRunner/DaemonRunner/Service/App/DaemonCompiler.cs
> +        public static Assembly GetCompiledAppAssembly(out CollectibleAssemblyLoadContext alc, string codeFolder, ILogger logger)
This once worked but was moved to be compiled by container cause I wanted to support custom csproj file. We need to be able to support this in that case. Would be great if we manage this.

2020-08-27 18:06 UTC, helto4real commented on src/DaemonRunner/DaemonRunner/Service/App/DaemonCompiler.cs
> +                    //embeddedTexts.Add(EmbeddedText.FromSource(csFile, sourceText));
hmm wonder if it was used once in error log for compile errors... Not sure.

2020-08-27 18:10 UTC, helto4real commented on src/DaemonRunner/DaemonRunner/Service/RunnerService.cs
> -                    alc.Unload();
Ohh good find

2020-08-27 19:15 UTC, BeeHiveJava commented on src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs
> +            return false;
```suggestion
           return bool.TryParse(value, out var boolResult) && boolResult;
```

2020-08-27 19:17 UTC, BeeHiveJava commented on src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs
> +            if (BypassLocalAssemblyLoading())
I'm wondering if it would be better to inject both compilers and pick the right one at runtime (depending on the ENV var) in a factory. But this is something easily added in the future. It was just a thought I had.

2020-08-27 19:19 UTC, BeeHiveJava commented on src/DaemonRunner/DaemonRunner/Infrastructure/Extensions/AssemblyExtensions.cs
> +            return assembly.GetTypes().Where(x => x.IsClass && x.IsSubclassOf(typeof(T)));
Actually I don't think this covers all cases. I think we should check whether the types are:
- A class
- Not abstract
- Not generic

2020-08-27 19:21 UTC, BeeHiveJava commented on src/DaemonRunner/DaemonRunner/Service/App/DaemonCompiler.cs
> +                    //embeddedTexts.Add(EmbeddedText.FromSource(csFile, sourceText));
I'd rather remove it than leaving a comment, if it serves no purpose.

2020-08-27 19:22 UTC, BeeHiveJava requested changes
Great changes!

2020-08-28 07:58 UTC, helto4real commented on src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs
> +            if (BypassLocalAssemblyLoading())
Ohh right, interesting idea @BeeHiveJava

2020-08-28 10:55 UTC, asherw commented on src/DaemonRunner/DaemonRunner/Service/App/DaemonAppCompiler.cs
> +        public IEnumerable<Type> GetApps()
I'm angling for the app to register all the apps in the DI container.  POC didn't require this, it just did reflection over app assembly and registered them in the DI container, but as I'm implementing changes things are turning out slightly different than I expected.

2020-08-30 11:46 UTC, helto4real commented on src/DaemonRunner/DaemonRunner/Service/App/DaemonAppCompiler.cs
> +        public IEnumerable<Type> GetApps()
Got it

2020-08-30 11:49 UTC, helto4real commented
> Great changes!

Agree nice

2020-09-02 11:13 UTC, helto4real commented
@asherw is your plan to update the PR? Or do you want to merge it as is?

2020-09-13 12:09 UTC, BeeHiveJava approved these changes

2020-09-13 13:11 UTC, merged