Entity Extensions
net-daemon/netdaemon pull request #337
Opened 2021-03-23 04:55 UTC by ngelotte

## Breaking change

## Proposed change

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2021-03-23 05:26 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/BinarySensorEntity.cs
> +        public bool IsOn
I would do these like
public bool IsOn => State == "on"

the ?? "unknown" is not needed here I think because null does not equal "on"

2021-03-23 05:26 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static IObservable<(EntityState Old, EntityState New)> StateAllChanges(this IEnumerable<RxEntityBase> entities, NetDaemonRxApp app)
I wanted to do this without passing the NetDaemonRxApp app parameter here. I think it should be possible because these entities allready have a refrence to the app, it is just not exposed.

Maybe It can also be done by calling StateChanges on each entity and then combining the IObservables (not sure how that works in RX but I think it would be possible

2021-03-23 05:26 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        /// </summary>
This can be written as

public static bool AreAllOn(this IEnumerable<SwitchEntity> entities) => entities.All(e => e.IsOff)

Which also makes this method a bit less usefull I guess

2021-03-23 05:26 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static bool IsOn(this EntityState entityState)
Having IsOn both on the State and the Entity object seems a bit redundant

2021-03-23 05:26 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/SunEntity.cs
> +
You could use an overload for the constructor instead of a default parameter value, like

public SunEntity(INetDaemonRxApp daemon) : this(daemon, new [] { "sun.sun"} )
        {
        }

2021-03-23 05:26 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/SwitchEntity.cs
> +        public bool IsOn
Adding these on/offf properties on the specific entities will make it harder to use them generically. 
I am not sure about the HA structure, if 'on / off' is appliccable for all or most entities I would put them on the base class or maybe as extension methods for the base class. Or maybe just leave them as extention method just on the state object.

2021-03-23 06:11 UTC, ngelotte commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static IObservable<(EntityState Old, EntityState New)> StateAllChanges(this IEnumerable<RxEntityBase> entities, NetDaemonRxApp app)
I agree. It would be great to not have to pass the app. But I am not sure the best way to do that. Probably wait to see if anyone else has some good ideas here.

2021-03-23 06:12 UTC, ngelotte commented on src/App/NetDaemon.App/Common/Reactive/Services/SunEntity.cs
> +
Perfect. I knew I was missing something.

2021-03-23 06:15 UTC, ngelotte commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static bool IsOn(this EntityState entityState)
The reason I put it here is because then you can using it in the where statements. Like this:
`PirSensors.StateChanges(this)
                        .Where(e => e.New.IsOn())
                        .Subscribe(e => ....`

They are kind of redundent but they serve similar but different purposes in my mind.

2021-03-23 06:16 UTC, ngelotte commented on src/App/NetDaemon.App/Common/Reactive/Services/BinarySensorEntity.cs
> +        public bool IsOn
Good thinking. I will update

2021-03-23 06:20 UTC, ngelotte commented on src/App/NetDaemon.App/Common/Reactive/Services/SwitchEntity.cs
> +        public bool IsOn
I don't use a lot of the entity types so I don't know how many of them have a concept of on/off. I like that they can be customized to make sense for what the the entity types are supposed to do. They are already kind of the generizied version of that class of thing for Home Assistant. The generated entities would have every property that home assistant exposes. For example the ClimateEntity has it's own concepts, as does Lock and Vacuum. I don't want IsOn or IsOff showing up on things where it would not make sense.

2021-03-23 06:23 UTC, ngelotte commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        /// </summary>
Did not think of using All. I like it.

2021-03-23 11:58 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/SwitchEntity.cs
> +        public bool IsOn
RxEntity has TurnOff() and TurnOff() on it, probably because many entities provide a turn_on / turn_off service. I see in my HAS deveoper tools however this is not the case for all of them.

2021-03-23 17:13 UTC, BeeHiveJava commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static IObservable<(EntityState Old, EntityState New)> StateAllChanges(this IEnumerable<RxEntityBase> entities, NetDaemonRxApp app)
Hey what about `entities.Select(e => e.StateAllChanges).Merge();`.

I don't have time to test this, but it should work. We might want to limit concurrency in the `Merge` operation though.

2021-03-23 18:15 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static IObservable<(EntityState Old, EntityState New)> StateAllChanges(this IEnumerable<RxEntityBase> entities, NetDaemonRxApp app)
I think merge is exacly what I ment. I do not think it will cause any actual concurrency issues. The observabkes that are returned from the StateChange properties of each entity are really just all different filters on the original same observable. Merge will just combine the results of these filters again onto a single stream

2021-03-23 18:38 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static IObservable<(EntityState Old, EntityState New)> StateAllChanges(this IEnumerable<RxEntityBase> entities, NetDaemonRxApp app)
Maybe this method should be called
MergeStateAllChanges()

I found it a bit strange to have a Method in IEnumerable<rxEntityBase> with the same name as a property on some other classes. Starting with a verb also makes more sense for a method.

2021-03-24 20:26 UTC, helto4real requested changes
Thanks, looks great overall.

I do have some changes, the tests of "merge" part. Just comment or even better write tests for it. Also the "IsOn" on the state class I think is not great since it has all kind of states for entities that does not have on/off states as well. I am prepared to change my mind about that if there are a good reason to.

2021-03-24 20:26 UTC, helto4real commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static void TurnAllOff(this IEnumerable<SwitchEntity> entities)
I would prefere to have just `TurnOn` cause of context you would know it has to do with many switches given you call your variable like `living_room_lights.TurnOn()` looks nicer imo. I will not comment rest.

2021-03-24 20:26 UTC, helto4real commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static bool AreAllOn(this List<SwitchEntity> entities) => entities.All(e => e.IsOn);
Same comment as before. Remove "All"? We keep "Are" so like `if (livingroom_ligts.AreOn(){}`

2021-03-24 20:26 UTC, helto4real commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static IObservable<(EntityState Old, EntityState New)> StateAllChanges(this IEnumerable<RxEntityBase> entities, NetDaemonRxApp app)
I will wait with merging this PR until you confirm it tests ok. But l do not have any idea how "not pass app" ether.

2021-03-24 20:26 UTC, helto4real commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static bool IsOn(this EntityState entityState)
I agree with Frank on this one. How do they serve different purposes? Think API should kept as small as possible. This is also on the general "EntityState" class. That means that entities that also not implement on/off will have this method.

2021-03-24 20:26 UTC, helto4real commented on src/App/NetDaemon.App/Common/Reactive/Services/LightEntity.cs
> +        public bool IsOn
Here it makes sense to have "IsOn" since it is a light after all

2021-03-24 20:26 UTC, helto4real commented on src/App/NetDaemon.App/Common/Reactive/Services/SwitchEntity.cs
> +        public bool IsOn
Should be ok for individial entities that actually have On/Off states. I rather have  them on those than the State object.

2021-03-25 18:28 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static bool AreAllOn(this List<SwitchEntity> entities) => entities.All(e => e.IsOn);
Part of my point was that because you can also write

if (livingroom_ligts.All(l => l.IsOn){}

I do not think this method is very usefull and maybe better to leave it out.

It is also more clear to me that it means all lights are on reather than maybe at least one, innwhich vase I would write

Lighys.Any(l => l.IsOn)

2021-03-25 20:25 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static IObservable<(EntityState Old, EntityState New)> StateAllChanges(this IEnumerable<RxEntityBase> entities, NetDaemonRxApp app)
The Merge() suggested by @BeeHiveJava eliminates the need for the app parameter.

I did take a look at how Merge is implemented. It is a bit more complicated than just filtering on any of the id's because it needs to handle concurrent evens from multiple sources which will not happen in this case. So maybe there is some overhead. Removing the parameter from the api however seems to out weigh the possible overhead to me

2021-03-25 20:42 UTC, BeeHiveJava commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static IObservable<(EntityState Old, EntityState New)> StateAllChanges(this IEnumerable<RxEntityBase> entities, NetDaemonRxApp app)
I agree with @FrankBakkerNl, concurrency is not an issue here and the overhead outweighs the api design. But we could always pass a parameter to `Merge` to make this choice explicit.

```C#
const int MaxConcurrency = 1; // Move this elsewhere, possibly constants module.
entities.Select(e => e.StateAllChanges).Merge(MaxConcurrency);
```

2021-03-25 20:56 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static IObservable<(EntityState Old, EntityState New)> StateAllChanges(this IEnumerable<RxEntityBase> entities, NetDaemonRxApp app)
Did not know about the max concurrency parameter. I would not bother moving it if 1 is e sensibke value here.

Alternative would be to have the Entity class make its App field accessible via an internal property. Then we can check if they are all the same (which would most likely be the case) and use that. Otherwise we so the merge

2021-03-25 21:00 UTC, ngelotte commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static IObservable<(EntityState Old, EntityState New)> StateAllChanges(this IEnumerable<RxEntityBase> entities, NetDaemonRxApp app)
I will try it with just Merge. I think the overhead will be minimal. I think I will leave it as the default(no max concurrency parameter) just to be safe and le the RX library function as intended.

2021-03-25 21:20 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static IObservable<(EntityState Old, EntityState New)> StateAllChanges(this IEnumerable<RxEntityBase> entities, NetDaemonRxApp app)
_If you pass an Enumerable or Observable of Observables, you have the option of also passing in an integer indicating the maximum number of those Observables it should attempt to be subscribed to simultaneously. Once it reaches this maximum subscription count, it will refrain from subscribing to any other Observables emitted by the source Observable until such time as one of the already-subscribed-to Observables issues an onCompleted notification._

2021-03-25 21:21 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static IObservable<(EntityState Old, EntityState New)> StateAllChanges(this IEnumerable<RxEntityBase> entities, NetDaemonRxApp app)
Seems this maxConxurrent is indeed not what we need here

2021-03-26 14:50 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/BinarySensorEntity.cs
> +        public override SwitchEntityState? EntityState
Should not this be BinaryEntityState?

2021-03-26 14:50 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/BinarySensorEntity.cs
> +        {
Allmost all of these get properties can be written using the => syntax which will make most of them simple one-liners. Try to avoid null checks on non-nullable fields (not sure if this can be null here)

public override SwitchEntityState? EntityState => base.EntityState == null ? null : BinaryEntityState(base.EntityState )

2021-03-26 14:50 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +                    if (entity.IsOn)
If this check is needed it should be inside entity.TurnOff();

2021-03-27 05:08 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static bool AreOn(this List<SwitchEntity> entities) => entities.All(e => e.IsOn);
I had another comment on these AreOn / AreOff methods which seems to got lost due to the last commit

I think these methods have very limited value , now you an type
myLights.AreOn
instead of
myLights.All(l = l.IsOn)

I have no problem typing the last, so personally I would not add these small helpers to NetDeamon where they need to be mainataned, documented etc.

2021-03-27 05:08 UTC, FrankBakkerNl commented on src/App/NetDaemon.App/Common/Reactive/Services/EntityGroupExtensions.cs
> +        public static bool AreOff(this List<SwitchEntity> entities) => entities.All(e => e.IsOn);
Should be IsOff I guess

2021-11-01 21:40 UTC, FrankBakkerNl commented
I think most of what was in this PR is now also present in the new HassModel. and #498  #499

2021-11-01 21:40 UTC, closed without merging