add enum support to yaml
net-daemon/netdaemon pull request #396
Opened 2021-06-24 12:30 UTC by Zorgino

## Breaking change

## Proposed change
add support of enums on app's yaml config. 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

[docs-repository]: https://github.com/net-daemon/docs

2021-06-24 13:08 UTC, BeeHiveJava commented
We should add tests for this.

2021-06-25 06:05 UTC, helto4real commented
Thanks for the PR, please add some tests. Thanks :)

2021-06-27 07:12 UTC, Zorgino commented
@BeeHiveJava, @helto4real , added tests

2021-06-27 10:27 UTC, helto4real requested changes
Thanks for the contribution. looks good. Please fix the naming warnings or use attributes to allow naming if it makes sense. These warnings will be reported by Sonar Cube as code smells and we wanna keep these to a minimum.

2021-06-27 10:27 UTC, helto4real commented on tests/NetDaemon.Daemon.Tests/DaemonRunner/Config/TestEnum.cs
> +    public enum TestEnum
Please fix the warning of naming. This will be an error when Sonar Cube works for forks again.

2021-06-28 16:49 UTC, helto4real approved these changes
Good job thanks a lot

2021-06-28 16:49 UTC, merged