Revert state manager
net-daemon/netdaemon pull request #415
Opened 2021-07-22 22:35 UTC by FrankBakkerNl

## Breaking change

## Proposed change

Revert of StateManager storing HassStates iso EntityState

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ X] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2021-07-22 22:40 UTC, FrankBakkerNl commented on src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
> -            StateManager.States.Select(s => s.MapWithArea(GetAreaForEntityId(s.EntityId)));
This line might have been a big problem. It maps all entities in the cache if the entire IEnumerable is consumed

2021-07-23 09:51 UTC, helto4real requested changes
Looks good. Make the CI pass and we are good to go.

2021-07-23 09:51 UTC, helto4real commented on src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
> -            StateManager.States.Select(s => s.MapWithArea(GetAreaForEntityId(s.EntityId)));
That makes sens since it could potentially or even always iterate through all entities.

2021-07-23 12:04 UTC, helto4real approved these changes

2021-07-23 12:04 UTC, merged