Adds GH container registry for release and manual release
net-daemon/netdaemon pull request #506
Opened 2021-11-07 18:29 UTC by helto4real

## Breaking change

## Proposed change

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2021-11-07 18:56 UTC, ludeeus requested changes

2021-11-07 18:56 UTC, ludeeus commented on .github/workflows/push_docker_manual.yml
> +      - name: 🔓 Login to GitHub Container Registry
I would use the same action to log in to the dockerhub registry for consistency

2021-11-07 18:56 UTC, ludeeus commented on .github/workflows/push_docker_manual.yml
>              --tag "netdaemon/netdaemon:feature-${{ github.event.inputs.tag }}"
```suggestion
            --tag "netdaemon/netdaemon:feature-${{ github.event.inputs.tag }}" \
```

2021-11-07 18:56 UTC, ludeeus commented on .github/workflows/tags_docker.yml
> +      - name: 🔓 Login to GitHub Container Registry
I would use the same action to log in to the dockerhub registry for consistency

2021-11-07 18:56 UTC, ludeeus commented on .github/workflows/tags_docker.yml
>              --tag netdaemon/netdaemon:${{ steps.version.outputs.version }}
```suggestion
            --tag netdaemon/netdaemon:${{ steps.version.outputs.version }} \
```

2021-11-07 19:23 UTC, BeeHiveJava commented on .github/workflows/tags_docker.yml
> +            --tag ghcr.io/net-daemon/netdaemon:${{ steps.version.outputs.version }}
Should we also push a 'latest' tag here?

2021-11-08 17:19 UTC, helto4real commented on .github/workflows/tags_docker.yml
> +            --tag ghcr.io/net-daemon/netdaemon:${{ steps.version.outputs.version }}
hmm yea that would be a good idea.

2021-11-08 17:22 UTC, helto4real commented on .github/workflows/push_docker_manual.yml
> +      - name: 🔓 Login to GitHub Container Registry
yepp, missed that one in the dev one

2021-11-08 17:28 UTC, ludeeus approved these changes

2021-11-08 17:40 UTC, merged