Automatically remove unused app state input booleans
net-daemon/netdaemon pull request #657
Opened 2022-02-03 21:17 UTC by helto4real

## Breaking change

## Proposed change

Removes unused input boolean helpers for non existing apps

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2022-02-03 21:23 UTC, ludeeus commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
> +            case ApplicationState.Disabled when isEnabled:
```suggestion
            default:
```
It's a boolean so can only have 2 values?

2022-02-03 21:26 UTC, FrankBakkerNl commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
> +            case ApplicationState.Disabled when isEnabled:
the state is an enum that can be Enabled, disabled or some other states I think. But I agree the switch here could probably better be replaces with a normal if

2022-02-03 21:28 UTC, ludeeus commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
> +            case ApplicationState.Disabled when isEnabled:
lol, yeah I was about to comment 2 things;
1) This should probably be just a if
2) @ludeeus you have no clue what you are talking about 
:smile:

2022-02-03 21:28 UTC, FrankBakkerNl commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
> +    public void Dispose()
Please make Initialize the first method after the constructor and dispose the last of the class

2022-02-03 21:32 UTC, FrankBakkerNl commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateRepository.cs
> +        if (applicationIds.Count == 0)
This seems odd, if there are no more apps you would expect all switches to be removed

2022-02-03 21:34 UTC, helto4real commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
> +    public void Dispose()
Damn Rider does this every time :) I gonna see if there is a way to make it not do it!

2022-02-03 21:34 UTC, helto4real commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateRepository.cs
> +        if (applicationIds.Count == 0)
Indeed.

2022-02-03 21:38 UTC, FrankBakkerNl commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateRepository.cs
> +        var notUsedHelperIds = helpers.Where(n =>
This Contains() will execute the select() again for each helper causing each id to be mapped n^2 times. 
Instead of a where you could use Except() here that will use a hashTable interanlly

2022-02-03 21:41 UTC, helto4real commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateRepository.cs
> +        if (applicationIds.Count == 0)
You were right. I added test for it as well

2022-02-03 21:43 UTC, FrankBakkerNl commented on src/Runtime/NetDaemon.Runtime/Internal/EntityMapperHelper.cs
> +            lastChar = c;
I think you should check if tha last appended char was an _, not the last input char. Now you could still get two _ in a row in the output

2022-02-03 21:55 UTC, FrankBakkerNl commented on src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
> +
double newline

2022-02-03 21:58 UTC, helto4real commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateRepository.cs
> +        var notUsedHelperIds = helpers.Where(n =>
The two lists are of two different types and I need the type that are the class to get the original Id back. It is such small lists so it will have no performance issues but will make it more complicated. If you have a suggestion please let me know but I cannot see it :)

2022-02-03 22:01 UTC, FrankBakkerNl requested changes
finishe review, just some minors

2022-02-03 22:02 UTC, FrankBakkerNl commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateRepository.cs
> +        var notUsedHelperIds = helpers.Where(n =>
Maybe Except is not easy here, then yoy could also just add ToHashSet at line 59

2022-02-03 22:03 UTC, helto4real commented on src/Runtime/NetDaemon.Runtime/Internal/EntityMapperHelper.cs
> +            lastChar = c;
I do not know any way to get last character added from a StringBuilder. But I think this logic still works.

2022-02-03 22:04 UTC, helto4real commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
> +            case ApplicationState.Disabled when isEnabled:
Haha

2022-02-04 08:07 UTC, helto4real commented on src/Runtime/NetDaemon.Runtime/Internal/AppStateRepository.cs
> +        var notUsedHelperIds = helpers.Where(n =>
Good suggestion. Done

2022-02-04 09:54 UTC, FrankBakkerNl approved these changes

2022-02-04 09:54 UTC, merged