Mqtt extension to create an update entities in HA
net-daemon/netdaemon pull request #658
Opened 2022-02-04 08:38 UTC by eugeneniemand

## Breaking change

## Proposed change

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2022-02-04 12:43 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttConfiguration.cs
> +public class MqttConfiguration
What about TLS support?

2022-02-04 12:43 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttConfiguration.cs
> +public class MqttConfiguration
https://www.home-assistant.io/docs/mqtt/certificate/

2022-02-04 12:45 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttEntityManager.cs
> +        return $"homeassistant/{domain}/{entityId}";
This should be configurable: https://www.home-assistant.io/docs/mqtt/discovery/#discovery_prefix

2022-02-04 12:46 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttConfiguration.cs
> +public class MqttConfiguration
Maybe we can add this at a later point, it's not blocking current functionality.

2022-02-04 12:46 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +                                                         .WithRetainFlag()
Should this always retain? I think we should make that configurable as well. Retaining by default is sensible though.

2022-02-04 12:47 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +        _logger.LogDebug($"Sending to {message.Topic}: {message.ConvertPayloadToString()}");
You can make use of structured logging here.

2022-02-04 12:48 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +        await ConnectAsync(mqttClient);
Is opening a connection every time a good idea? Should we pool the connection somewhere?

2022-02-04 12:49 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMqttEntityManager.cs
> +    Task RemoveAsync(string domain, string entityId);
I'm wondering if we can make some kind of common value object here.

2022-02-04 12:50 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttEntityManager.cs
> +        return $"homeassistant/{domain}/{entityId}";
`homeassistant` Is the correct default.

2022-02-04 12:54 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMqttEntityManager.cs
> +    Task CreateAsync(string domain, string deviceClass, string entityId, string name);
Would it be strange to swap around the `deviceClass` and `entityId` here? Then the starting arguments have the same position for every call here.

2022-02-04 12:56 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +        if (string.IsNullOrEmpty(_mqttConfig.Host))
This check is a little strange to me. Why is it only checking the host? And if the configuration section is missing from the appsettings, does it not throw an error somewhere?

2022-02-04 13:04 UTC, skotl commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +        await ConnectAsync(mqttClient);
Nope - it's supposed to be short lived (and actually has a default timeout of 10 seconds)

2022-02-04 13:28 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +        await ConnectAsync(mqttClient);
Oh cool!

2022-02-04 13:58 UTC, skotl commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +        await ConnectAsync(mqttClient);
Actually, turns out that the MQTTNet project also supplies a managed mqtt client as an extension, which automatically reconnects on disconnection. It probably makes more sense to include that rather than the low-level client that is provided here.
I'll unresolve for now - I don't think it's blocking (as calls to mqtt will be relatively infrequent and it's not expensive to reconnect) but it's a useful improvement for later.

2022-02-04 14:14 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +        await ConnectAsync(mqttClient);
That is also what I understood from the documentation. This already uses the managed client, it's just that it's disposed and recreated on every call.

2022-02-04 20:41 UTC, BeeHiveJava commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttEntityManager.cs
> +        return $"{discoveryPrefix}/{domain}/{entityId}";
Alternatively if you make this methods non-static, you don't have to pass the first argument and can get it from the options directly.

2022-02-04 23:25 UTC, eugeneniemand commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +        if (string.IsNullOrEmpty(_mqttConfig.Host))
It actually still creates an instance of the class with all the default values

2022-02-04 23:27 UTC, eugeneniemand commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttEntityManager.cs
> +        return $"{discoveryPrefix}/{domain}/{entityId}";
Done

2022-02-05 06:23 UTC, helto4real requested changes
I think we should use `ConfigureAwait(false)` and not supress those. Also keep only the interfaces used by users public.

2022-02-05 06:23 UTC, helto4real commented on dev/DebugHost/apps/Extensions/MqttEntityManagerApp.cs
> +    [SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>")]
I do not think we should supress anything other than the CA1031 here

2022-02-05 10:41 UTC, skotl commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +        var options = new MqttClientOptionsBuilder()
The Connect or the options builder?
This is the lightweight client whose connection is time sensitive (timeout is 10 seconds, I believe) so it's called when the message is ready to be sent. There is a managed client available as an extension that we could (should?) include, which maintains the connection.

2022-02-05 10:43 UTC, skotl commented on dev/DebugHost/apps/Extensions/MqttEntityManagerApp.cs
> +            await _manager.CreateAsync("binary_sensor", "motion", "manager_test", "Manager Test");
This is just the test app, which won't (or shouldn't!) be called by external apps - just a question of style really, but it's not a hardship to add this so we should do it.

2022-02-05 10:45 UTC, skotl commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMessageSender.cs
> +public interface IMessageSender
It's public as it is in the constructor of the public `IMqttEntityManager` so that it can be supplied via DI.
Not sure how we work around that - do you have any suggestions?

2022-02-05 10:54 UTC, skotl commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +        var options = new MqttClientOptionsBuilder()
Move options builder to constructor

2022-02-05 10:55 UTC, skotl commented on dev/DebugHost/apps/Extensions/MqttEntityManagerApp.cs
> +        catch (Exception e)
This is just a catch-all to aid debugging in the test app - is that ok?

2022-02-05 11:01 UTC, helto4real commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMessageSender.cs
> +public interface IMessageSender
It should be fine to make MqttManager internal. Then we only expose the IMqttManager for users.

2022-02-05 11:11 UTC, skotl commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMessageSender.cs
> +public interface IMessageSender
Now internal, alongside `MqttEntityManager`

2022-02-05 11:11 UTC, helto4real approved these changes
Good job @eugeneniemand and @skotl  really looking forward trying this!

2022-02-05 11:11 UTC, skotl commented on dev/DebugHost/apps/Extensions/MqttEntityManagerApp.cs
> +            await _manager.CreateAsync("binary_sensor", "motion", "manager_test", "Manager Test");
Done

2022-02-05 11:15 UTC, merged