More optionality around entity creation, simplified public method signatures
net-daemon/netdaemon pull request #662
Opened 2022-02-05 23:15 UTC by skotl

Provide more optionality around the create-entity requests.
Provide better defaults (unique_id, name) to ensure that a basic request to create an entity succeeds.
Change signatures of Create, Update and Remove to use a single `entityId` construct (like "sensor.kitchen_temp") rather than pass domain and identifier.
Expand test / sample application to show how to create a switch as well as different examples of optional arguments.

## Breaking change
This is a breaking change - the requests to `CreateAsync`, `UpdateAsync` and `RemoveAsync` now require a single `entityId` argument (e.g. "sensor.kitchen_heat") rather than specifying a domain and identifier.

## Proposed change
Provide better default options to increase the chance of the creation succeeding.
Optional record parameter to `CreateAsync()` public method to allow caller to override each of these arguments.

Added more examples

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [x] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request: docs need to be updated - I'll do that

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2022-02-06 01:14 UTC, eugeneniemand commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMqttEntityManager.cs
> +    Task UpdateAsync(string entityId, string state, object? attributes = null);
This seems to be dupicated

2022-02-06 01:15 UTC, eugeneniemand approved these changes

2022-02-06 01:39 UTC, skotl commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMqttEntityManager.cs
> +    Task UpdateAsync(string entityId, string state, object? attributes = null);
It's an overload to just supply an anonymous object rather than having to json.stringify the object

2022-02-06 07:35 UTC, helto4real commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMqttEntityManager.cs
> +    Task UpdateAsync(string entityId, string state, object? attributes = null);
I think we should only use the object? one. We should not make users use serializer to call an API.

2022-02-06 07:40 UTC, helto4real requested changes
I think we should stick to the `object?` version only. This is how the API:s looks like in the rest of the NetDaemon product. We should not let users have to use JsonSerializers them self. Otherwise this looks good!

2022-02-06 07:40 UTC, helto4real commented on dev/DebugHost/apps/Extensions/MqttEntityManagerApp.cs
>  [Focus]
Remove this before merge

2022-02-06 12:53 UTC, skotl commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMqttEntityManager.cs
> +    Task UpdateAsync(string entityId, string state, object? attributes = null);
Done

2022-02-06 12:54 UTC, skotl commented on dev/DebugHost/apps/Extensions/MqttEntityManagerApp.cs
>  [Focus]
Oops - done

2022-02-07 16:38 UTC, helto4real approved these changes

2022-02-07 16:41 UTC, merged