Mqtt managed client
net-daemon/netdaemon pull request #664
Opened 2022-02-06 15:54 UTC by skotl

Migrate to managed MQTT client for more resilience

Note that this has a dependency on #662 

This is not a breaking change

## Breaking change
No

## Proposed change
Move to MqttNet.Extensions.ManagedClient away from the simplified client
Wrap this up in an assurer class that the `MessageSender` class depends on for assuring a connection is available.
Currently has a hard-coded retry timeout of 15 seconds.

## Type of change

- [x] Dependency upgrade - needs #662 
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to an existing integration) - resilience
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2022-02-06 19:28 UTC, helto4real requested changes

2022-02-06 19:28 UTC, helto4real commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +        var mqttClient = _assuredMqttConnection.GetClientOrThrow();
This should be async. Then you could await it with a CancellationToken that are time out for example. Now you mix sync/async code and that often leads to unpredictable results like blocking. You could for example provide the CancellationToken to this method and that should be used while waiting for connection.

2022-02-06 19:28 UTC, helto4real commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/AssuredMqttConnection.cs
> +    public IManagedMqttClient GetClientOrThrow()
As comment before. This method can be async. Provide a CancellationToken and use ConnectAsync here using the cancellation token for cancel the potentially long running task connecting. I am sure the Mqtt client has a way to provide a cancellation token to the connect method.

2022-02-06 19:28 UTC, helto4real commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/AssuredMqttConnection.cs
> +            Thread.Sleep(1000);
Using Thread.Sleep in a method that are not async but called from the async code could halt processing and create deadlocks.

2022-02-06 19:29 UTC, helto4real requested changes
The way of how async/sync code is written will be trouble I think. We should be able to make the GetClientOrThrow async.

2022-02-07 14:41 UTC, skotl commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
> +        var mqttClient = _assuredMqttConnection.GetClientOrThrow();
I don't think we need the cancellationtoken in the new approach now, as the managed MQTT client will have its own timeout mechanism - would you agree?

2022-02-07 14:41 UTC, skotl commented on src/Extensions/NetDaemon.Extensions.MqttEntityManager/AssuredMqttConnection.cs
> +    public IManagedMqttClient GetClientOrThrow()
As previous comment

2022-02-07 15:18 UTC, helto4real approved these changes
Looks way better now. Good job.

2022-02-07 18:49 UTC, helto4real commented
Closing this, already merged.

2022-02-07 18:49 UTC, closed without merging