Add option to specify Cron Job with Seconds
net-daemon/netdaemon pull request #828
Opened 2023-01-16 03:32 UTC by spelech

## Proposed change

## Type of change
- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Additional information

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2023-01-22 12:39 UTC, helto4real commented on src/Extensions/NetDaemon.Extensions.Scheduling/CronExtensions.cs
> +    public static IDisposable ScheduleCron(this IScheduler scheduler, string cron, Action action, bool hasSeconds = false)
Not familiar with the cron syntax on this but as a suggestion could we check for a pattern instead of providing a `hasSeconds` parameter? Even if it is not breaking it would be event better not to provide one I think.

2023-01-23 15:23 UTC, spelech commented on src/Extensions/NetDaemon.Extensions.Scheduling/CronExtensions.cs
> +    public static IDisposable ScheduleCron(this IScheduler scheduler, string cron, Action action, bool hasSeconds = false)
Hmm let me give that a whirl. Cronos apparently does not try to determine if seconds are present in the string based on their function requiring the Format specifier if we use seconds.  It could be as simple as checking the number of spaces present (4-> no seconds, 5 -> has seconds).

If that has weird edge cases, I could just create a new method `ScheduleCronFine` or something to denote that is has higher resolution available

2023-01-24 13:51 UTC, mutzl commented on src/Extensions/NetDaemon.Extensions.Scheduling/CronExtensions.cs
> +    public static IDisposable ScheduleCron(this IScheduler scheduler, string cron, Action action, bool hasSeconds = false)
A boolean `hasSeconds` seems absolutely fine to me.

Or alternatively directly passing the `Cronos.CronFormat`
``` C#
public static IDisposable ScheduleCron(this IScheduler scheduler, string cron, Action action, CronFormat format = CronFormat.Standard)
```
A more sophisticated parser ( = automatically detect pattern with seconds) could be a feature request in the Cronos lib.

2023-01-25 18:33 UTC, helto4real commented on src/Extensions/NetDaemon.Extensions.Scheduling/CronExtensions.cs
> +    public static IDisposable ScheduleCron(this IScheduler scheduler, string cron, Action action, bool hasSeconds = false)
Agree if it complicates things a lot it is not worth it!

2023-02-06 06:58 UTC, FrankBakkerNl requested changes

2023-02-06 06:58 UTC, FrankBakkerNl commented on src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/CronTests.cs
> +        #region Cron with Seconds
Why not a separate test instead of regions?

Also this does not really test the seconds really work, but you could argue that is a feature or Cron.Net and not this extansion

2023-02-06 07:00 UTC, FrankBakkerNl commented on src/Extensions/NetDaemon.Extensions.Scheduling/CronExtensions.cs
> +    public static IDisposable ScheduleCron(this IScheduler scheduler, string cron, Action action, bool hasSeconds = false)
I Like the bool, becaue it does not expose the CRON library to the end user so we could change that in the future if needed

2023-02-06 14:40 UTC, FrankBakkerNl approved these changes

2023-02-06 14:50 UTC, merged