Guide users to use WhenStateIsFor with a IScheduler instance.
net-daemon/netdaemon pull request #864
Opened 2023-04-24 18:59 UTC by Barsonax

## Breaking change

## Proposed change

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #801 
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2023-04-25 04:44 UTC, helto4real commented
Not sure why you want to obsolete this? Please explain.

2023-04-25 17:44 UTC, Barsonax commented
Passing in a injected IScheduler is the more correct approach which is also unit testable.

However since ppl might be using WhenStateIsFor without IScheduler it will be breaking if you completely remove it.

2023-04-27 17:07 UTC, helto4real commented
> We discussed this some time ago when Rick created the issue for this. I agree it is preferred for several reasons to pass the Scheduler. This will now give a warning when you don't.
> 
> Someone might have a case where not passing the scheduler is 'ok'. Maybe if you only ever have short times where it is no problem if the event fires after the app unloads AND are not interested in Unit testing.
> 
> So the trade off is between preventing user from a mistake vs forcing users to pass a scheduler while it's not really needed.

I will not have user "have to" pass it. Warning should be ok. Not worth it to make it a breaking change. What you think @FrankBakkerNl ? Should we go with this?

2023-04-27 17:27 UTC, FrankBakkerNl commented
I think so, if ever we would change our minds we can just remove the obsolete attribute

2023-04-27 17:30 UTC, FrankBakkerNl requested changes

2023-04-27 17:30 UTC, FrankBakkerNl commented on src/HassModel/NetDeamon.HassModel/StateObservableExtensions.cs
> +        IScheduler scheduler)
I think this now does require a 
ArgumentNullExcpetion.ThrowIfNull(scheduler) because you cannot rely on clients using nullable refreces

2023-04-30 19:55 UTC, Barsonax commented on src/HassModel/NetDeamon.HassModel/StateObservableExtensions.cs
> +        IScheduler scheduler)
Yes strictly speaking that would be the case. Might as well check the other parameters as well then.

2023-05-02 17:50 UTC, FrankBakkerNl approved these changes

2023-05-02 20:24 UTC, merged