Add interfaces
net-daemon/netdaemon pull request #897
Opened 2023-07-22 16:06 UTC by x00Pavel

## Proposed change

Add base interfaces for generated Entities.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: #896 
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2023-07-22 18:55 UTC, FrankBakkerNl requested changes

2023-07-22 18:55 UTC, FrankBakkerNl commented on src/HassModel/NetDeamon.HassModel/Entities/Interfaces/IOnOffTarget.cs
> +public interface IToggleParameters
I don't think these interfaces are needed

2023-07-22 18:55 UTC, FrankBakkerNl commented on src/HassModel/NetDeamon.HassModel/Entities/Interfaces/IOnOffTarget.cs
> +public interface IOnOffTarget
This could be derived from IServiceTarget. That would even make it possible to have a default implementation of these methods that actually works

2023-07-22 18:55 UTC, FrankBakkerNl commented on src/HassModel/NetDeamon.HassModel/Entities/Interfaces/IOnOffTarget.cs
> +    public static void Toggle(long? transition = null, object? rgbColor = null, object? colorName = null, object? hsColor = null, object? xyColor = null, object? colorTemp = null, long? kelvin = null
The TurnOn and Toggle with all these arguments are specific to lights, not for all OnOff Entities

2023-07-22 18:55 UTC, FrankBakkerNl commented on src/HassModel/NetDeamon.HassModel/Entities/Interfaces/IServiceTarget.cs
> +public interface IServiceTarget: IEntity
Should not derive from IEntity. I don't think we need IEntity for this, I do want to introduce it later maybe as part of another feature so preferably I would not add it now and lock into a specific design yet

2023-07-23 07:55 UTC, x00Pavel commented on src/HassModel/NetDeamon.HassModel/Entities/Interfaces/IOnOffTarget.cs
> +public interface IToggleParameters
I added them to replace generated parameter classes. Without these, I wouldn't be able to specify methods with Parameter class.

2023-07-23 07:59 UTC, x00Pavel commented on src/HassModel/NetDeamon.HassModel/Entities/Interfaces/IServiceTarget.cs
> +public interface IServiceTarget: IEntity
Then `IServiceTarget` would need to have some attributes from `IEntity`. This is because of `EnumerableEntityExtensions` class. Inside it, there is a usage of `HaContext` and `StateAllChanges()` methods of the Entity class. This is the reason why I added this derivation. If you have any suggestion how to solve it, I'm don't have anything against it.

2023-07-23 13:59 UTC, FrankBakkerNl commented on src/HassModel/NetDeamon.HassModel/Entities/Interfaces/IOnOffTarget.cs
> +public interface IToggleParameters
The methods with parameter types will be in the generated code, so they are not needed here.

2023-07-29 12:09 UTC, x00Pavel commented
I've removed all methods from the interface to simplify the PR. To have empty interfaces is enough to fulfill needs of my request.

2023-07-29 12:15 UTC, x00Pavel commented
btw should I squash all commits?

2023-07-30 00:45 UTC, FrankBakkerNl commented
You can, but eventually we will squash commit the whole PR anyway. Keeping then separate at first makes reviewing changes easier

2023-08-15 22:25 UTC, FrankBakkerNl approved these changes

2023-08-20 18:15 UTC, helto4real approved these changes
Just some small stuff to fix before merge if you want to. I approve and let me know when it is ready for merge.

2023-08-20 18:15 UTC, helto4real commented on src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
> -		<GenerateDocumentationFile>True</GenerateDocumentationFile>
Why is this removed? We added docs just recently. Or am I missing something?

2023-08-20 18:15 UTC, helto4real commented on src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/EntitiesGenerator.cs
> -
Ther should be one line between functions.

2023-08-20 18:15 UTC, helto4real commented on src/debug/MyNDApp/apps/HassModel/MyInterfaceAutomation/InterfaceUsage.cs
> +[Focus]
Please remove Focus attribute before merge

2023-08-20 18:22 UTC, FrankBakkerNl commented on src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
> -		<GenerateDocumentationFile>True</GenerateDocumentationFile>
This is the codegen, it does not need API docs as we do not provide it as a nuget to be used in usercode

2023-08-20 19:45 UTC, helto4real commented
I got the answer from Frank regarding the docs removal. Rest is not important to fix. Merging

2023-08-20 19:45 UTC, merged