Cleaned some extensions
net-daemon/netdaemon pull request #898
Opened 2023-07-31 11:26 UTC by svrooij

## Proposed change

- Support for User Secrets by not overriding it.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Additional information

As discussed on discourt: https://discord.com/channels/686787269780176998/690899481046024233/1135518233458393108

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] Local tests pass. **Your PR cannot be merged unless tests pass**
- [X] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [X] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

2023-08-01 08:33 UTC, svrooij commented
After some thought I think the original code already supported user secrets, they were just overridden. The last config provider takes precedence. the `CreateDefaultBuilder` sets:

- Environment
- commandline arguments
- appsettings.json and appsettings.{environment}.json
- User secrets (if set to development)
- Environment variables
- commandline arguments

Then the `UseNetDaemonAppSettings` adds the following (which thus override the previous set):
- appsettings.json and appsettings.{env}.json
- environment
- yaml

This means that if you would remove the `token` from the app settings it would not get overriden. Either way, no need to set the configuration providers twise.

2023-08-01 19:23 UTC, helto4real requested changes
Looks good to me but I am not sure if environment is still working without the `AddEnvironmentVariables()` can you make sure that is not broken?

2023-08-01 19:23 UTC, helto4real commented on src/Runtime/NetDaemon.Runtime/Common/Extensions/HostBuilderExtensions.cs
> -                config.AddEnvironmentVariables();
This is missing? It is important that we still support using environment vars since the default container use them

2023-08-01 19:30 UTC, svrooij commented on src/Runtime/NetDaemon.Runtime/Common/Extensions/HostBuilderExtensions.cs
> -                config.AddEnvironmentVariables();
I’m 100% sure they still work.

source of the CreateDefaultBuilder: https://github.com/dotnet/runtime/blob/e43cba31e997e960205844b3f0541011ef732c29/src/libraries/Microsoft.Extensions.Hosting/src/HostingHostBuilderExtensions.cs#L256

But I also don’t trust the source, so I set a breakpoint inside the new RegisterYaml… and inspected the available config providers.

2023-08-01 19:33 UTC, svrooij commented
The failing test is strange, they all succeed locally, I explicitly checked.

2023-08-01 20:08 UTC, svrooij commented
@helto4real do you know how it’s possible for the coverage to go down if I removed code? That means the old code was not tested I guess? Want me to add tests for the yams settings part?

2023-08-03 07:42 UTC, helto4real commented
> The failing test is strange, they all succeed locally, I explicitly checked.

No it is ok! Sometimes it does this. The code was never tested in the first place and I am not sure how you would test this efficiently.

2023-08-03 07:42 UTC, helto4real approved these changes
Ok thanks for clarification and the PR!

2023-08-03 07:42 UTC, merged